parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: twip
    database_user: twipper
    database_password: twip
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 1474dfdcbe3972d91389449b9630f7b794c30a83
    database_path: null
